packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.13.1~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.1.18"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.1/zwave-js-ui-v9.13.1-linux-arm64.zip"
        arm64.sha256 = "373610030c6770eb9788d5055f5700cc7740b8937ec75de5f9eb2e4ef6e84517"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.1/zwave-js-ui-v9.13.1-linux-armv7.zip"
        armhf.sha256 = "ae1418c57225700d4588c154ec4b43826bc309787361a094e4db86c39504339a"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.1/zwave-js-ui-v9.13.1-linux.zip"
        amd64.sha256 = "7540e8ca0de03d5ff6d7f9a8bfe4a12f303d3690a9a5c93e914f7fd26cb0c308"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
