packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "8.25.0~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.1.18"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.25.0/zwave-js-ui-v8.25.0-linux-arm64.zip"
        arm64.sha256 = "d0a635a9ad08a96074bc93676679a11c916a124604de558b627aa0077b561561"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.25.0/zwave-js-ui-v8.25.0-linux-armv7.zip"
        armhf.sha256 = "05a8808e8d85931cbe0b17999de057ebc09651b427271d9934612cbff9eda642"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.25.0/zwave-js-ui-v8.25.0-linux.zip"
        amd64.sha256 = "38d0273daf8a21ceb258d91c6835ed02344765d25c93535d64b4050da496d997"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
