packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.13.2~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.1.18"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.2/zwave-js-ui-v9.13.2-linux-arm64.zip"
        arm64.sha256 = "b5c2248c6152b2fbcf2da47f795c8592d0f3fe8b7fbab7b14ed3e9450bf16dd9"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.2/zwave-js-ui-v9.13.2-linux-armv7.zip"
        armhf.sha256 = "0f4948fe9747cc624146b692ed792fac37b3ac3bf9039d760e8b8682427f69f9"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.13.2/zwave-js-ui-v9.13.2-linux.zip"
        amd64.sha256 = "99140e65345112367f220815ea0c73fc5b75752c2c0692f88d7d7cc0a451be3f"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
