packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.27.3~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.3/zwave-js-ui-v9.27.3-linux-arm64.zip"
        arm64.sha256 = "0bebdbb282f1051535aec48197cc48cac78d2005aba8c3b8890d124697639965"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.3/zwave-js-ui-v9.27.3-linux-armv7.zip"
        armhf.sha256 = "4236458f521759403f71c4a2cb27065ca4957314f5750750a2ef35dcfce9c228"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.3/zwave-js-ui-v9.27.3-linux.zip"
        amd64.sha256 = "87dc535d5b0cb8481ce08b9a901121e61fd0424c7d25d9c718e38fa2ce74895d"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
