packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.27.7~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.7/zwave-js-ui-v9.27.7-linux-arm64.zip"
        arm64.sha256 = "44895f2ebb33889818f5f048f300da90971e305342920d90192497d9fd704a4f"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.7/zwave-js-ui-v9.27.7-linux-armv7.zip"
        armhf.sha256 = "00a29e6af9cf7f5fc9b6312dbf24248cfef439f180b1d04f65c11a3149d5e5f2"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.27.7/zwave-js-ui-v9.27.7-linux.zip"
        amd64.sha256 = "ea9219519b0ba33d25bc99bba99e8151306f7f70baafbe4f4ea740e3b3798920"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
