packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.14.6~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.1.18"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.14.6/zwave-js-ui-v9.14.6-linux-arm64.zip"
        arm64.sha256 = "73cbf367d4a76bc92d41b15c245209ef058f240d8088340c78fae5fafe5d3039"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.14.6/zwave-js-ui-v9.14.6-linux-armv7.zip"
        armhf.sha256 = "5a7930994d6ad0a6488e81d0cd016ef7d6c5b36649cb7ecb04eaa217d408d671"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.14.6/zwave-js-ui-v9.14.6-linux.zip"
        amd64.sha256 = "f11945440420c10fe90e88a40605eb9d669f6f7fdfc5b11c7ecdb3c05399e53f"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
