packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "8.22.0~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.1.18"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.22.0/zwave-js-ui-v8.22.0-linux-arm64.zip"
        arm64.sha256 = "46987c5b61bdcd03c4d872b9b744962b1ef504b4aec36691a7ca838d7c3b9967"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.22.0/zwave-js-ui-v8.22.0-linux-armv7.zip"
        armhf.sha256 = "5cc4f74382280e637440900999b21f7364269dc7fbebc92d20181502b0603d61"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v8.22.0/zwave-js-ui-v8.22.0-linux.zip"
        amd64.sha256 = "ba3f0d9c3dbe1ee94e2e17831cece93a7a792b79828b0d0302b645514e757c45"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
