packaging_format = 2

id = "zwave-js-ui"
name = "Zwave-JS-UI"
description.en = "Full featured Z-Wave Control Panel and MQTT Gateway integrated with domoticz"
description.fr = "Panneau de controle Z-Wave et MQTT intégré avec Domoticz"

version = "9.22.0~ynh1"

maintainers = ["Krakinou"]

[upstream]
license = "MIT"
website = "https://zwave-js.github.io/zwave-js-ui/#/"
admindoc = "https://zwave-js.github.io/zwave-js-ui/#/"
userdoc = "https://www.domoticz.com/wiki/Zwave-JS-UI"
code = "https://github.com/zwave-js/zwave-js-ui"
fund = "https://liberapay.com/robertsLando/donate"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = [ "amd64", "armhf", "arm64" ]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "350M"
ram.build = "200M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zwavejsui"

    [install.init_main_permission]
    help.en = "If set public, anyone can access the app without login in YunoHost, you activate password protected login from within the app"
    help.fr = "Si publique, N'importe qui peut accéder à l'application sans se connecter à YunoHost, vous pouvez cependant activer une connection par mot de passe depuis l'application"
    type = "group"
    default = "all_users"

[resources]
        [resources.sources.main]
        arm64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.22.0/zwave-js-ui-v9.22.0-linux-arm64.zip"
        arm64.sha256 = "fb263fff27bd883280aca6b5e1ec78ee327dd30411aa90cb32bd123335c69fea"
        armhf.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.22.0/zwave-js-ui-v9.22.0-linux-armv7.zip"
        armhf.sha256 = "e4d9003fb7dabc13eac3c7004d3eab8d46de0a5b95b2f18e83e6caad89bbb8a8"
        amd64.url = "https://github.com/zwave-js/zwave-js-ui/releases/download/v9.22.0/zwave-js-ui-v9.22.0-linux.zip"
        amd64.sha256 = "d9b200a01818430409e9377e5ba3cd4c3242eb7373bd955fea66e87b92490b1b"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"

        autoupdate.asset.arm64 = ".*-arm64.zip"
        autoupdate.asset.amd64 = ".*-linux.zip"
        autoupdate.asset.armhf = ".*-armv7.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8091
