#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Configuring system user..."

usermod -d $install_dir $app

if grep dialout -q < /etc/group; then
	usermod -a -G dialout "$app"
fi
if grep i2c -q < /etc/group; then
	usermod -a -G i2c "$app"
fi
if grep gpio -q < /etc/group; then
	usermod -a -G gpio "$app"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD SWAP IF NEEDED
#=================================================
#https://github.com/zwave-js/zwave-js-ui/issues/2699
ynh_script_progression --message="Checking for RAM..."

total_memory=$(ynh_get_ram --total)
swap_needed=0

if [ $total_memory -lt $MEMORY_NEEDED ]; then
	# Need a minimum of 2Go of memory
	swap_needed=$(($MEMORY_NEEDED - $total_memory))
	ynh_script_progression --message="Adding $swap_needed Mo to swap..."
	SD_CARD_CAN_SWAP=1
	ynh_add_swap --size=$swap_needed

fi

#=================================================
# Install through npm
#=================================================
ynh_script_progression "Installing Zwave-JS-UI..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=1024" npm run build
popd

#=================================================
# REMOVE ADDITIONNAL SWAP
#=================================================
if [ $swap_needed > 0 ]; then
	ynh_script_progression --message="Remove additionnal swap..." --weight=2
	ynh_del_swap
fi

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Z-Wave integration" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="Listening on port" -t 30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
