#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Making sure dedicated system user exists..."

if grep dialout -q < /etc/group; then
	usermod -a -G dialout "$app"
fi
if grep i2c -q < /etc/group; then
	usermod -a -G i2c "$app"
fi
if grep gpio -q < /etc/group; then
	usermod -a -G gpio "$app"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="store"

#=================================================
# ADD SWAP IF NEEDED
#=================================================
#https://github.com/zwave-js/zwave-js-ui/issues/2699
ynh_script_progression "Checking for RAM..."

total_memory=$(ynh_get_ram --total)
swap_needed=0

if [ $total_memory -lt $MEMORY_NEEDED ]; then
	# Need a minimum of 2Go of memory
	swap_needed=$(($MEMORY_NEEDED - $total_memory))
	ynh_script_progression "Adding $swap_needed Mo to swap..."
	SD_CARD_CAN_SWAP=1
	ynh_add_swap --size=$swap_needed

fi

#=================================================
# Install through npm
#=================================================
ynh_script_progression "Installing Z-Wave-JS-UI..."

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app npm ci
    ynh_hide_warnings ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=1024" npm run build
popd

#=================================================
# REMOVE ADDITIONNAL SWAP
#=================================================
if [ $swap_needed > 0 ]; then
	ynh_script_progression "Remove additionnal swap..."
	ynh_del_swap
fi

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Z-Wave integration" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Listening on port" -t 30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
